---
#ansible_user: 'WIN2012SVR\srv-HOD-ansible'
#ansible_user: 'ABCD-Laptop\ABCD Family Admin'
ansible_user: 'srv-HOD-Ansible'
ansible_password: Ans1bl3
#ansible_password: Password123!
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
#ansible_winrm_transport: ntlm
