---
stuff: testcase
hostname: win2012server
ip_address: 10.0.1.3


disks:
  - OS:
      size: 50GB
      block_size: 32MB
      sector_size: 512
      allocation_unit_size: 4KB
      drive_letter: C
      bootable: true
  - InstallData:
      size: 10GB
      block_size: 32MB
      sector_size: 512
      allocation_unit_size: 64KB
      drive_letter: I
      bootable: false
  - Data:
      size: 5GB
      block_size: 32MB
      sector_size: 512
      allocation_unit_size: 64KB
      drive_letter: D
      bootable: false
  - Logs:
      size: 5GB
      block_size: 32MB
      sector_size: 512
      allocation_unit_size: 4KB
      drive_letter: L
      bootable: false
  - TempDB:
      size: 5GB
      block_size: 32MB
      sector_size: 512
      allocation_unit_size: 64KB
      drive_letter: E
      bootable: false
  - Backup:
      size: 5GB
      block_size: 32MB
      sector_size: 512
      allocation_unit_size: 64KB
      drive_letter: F
      bootable: false
